GET https://
Content-Type: application/json

{
  "imageUrl": "https://content.linkedin.com/lem/static/sc/etc-clientlibs/settings/wcm/designs/gandalf/clientlibs/resources/images/og-social-share-image.jpg",
  "platform": "linkedin",
  "content": "Hello, This is my first post in Linkedin"
}
